name: Ve2ydu
favicon: null
layout_spectrum: 0.04841067106463015
typography_spectrum: 0.8719934676773846
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.7903548623435199
  lightness: 0.1465076580643654
  saturation: 0.6058442695066333
  rhythmicContrast: 0.24464571406133473
purpose: []
